/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tareasprog;

/**
 *
 * @author gerardo.valenciano
 */
public class CalculadoraReloaded extends javax.swing.JFrame {
    double resultado = 0.0;
    String operacion = "";
    double numero = 0.0;
    

    /**
     * Creates new form primerJFrame
     */
    public CalculadoraReloaded() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jPanelCalculadora = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonPorcentaje = new javax.swing.JButton();
        jButtonRaiz = new javax.swing.JButton();
        jButtonPotencia = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonMultiplicacion = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonResta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonSuma = new javax.swing.JButton();
        jButtonSigno = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jBtnC = new javax.swing.JButton();
        jButtonPunto = new javax.swing.JButton();
        jTxtResultados = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonIgual = new javax.swing.JButton();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        jButtonPorcentaje.setText("%");
        jButtonPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorcentajeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPorcentaje);

        jButtonRaiz.setText("√");
        jButtonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaizActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRaiz);

        jButtonPotencia.setText("x^2");
        jButtonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotenciaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPotencia);

        jButtonDivision.setText("/");
        jButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDivision);

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        jButtonMultiplicacion.setText("X");
        jButtonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMultiplicacion);

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButtonResta.setText("-");
        jButtonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonResta);

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButtonSuma.setText("+");
        jButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSuma);

        jButtonSigno.setText("+-");
        jButtonSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSigno);

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton0);

        jBtnC.setText("C");
        jBtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnC);

        jButtonPunto.setText(".");
        jButtonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPuntoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPunto);

        jTxtResultados.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora de Gerardo");

        jButtonIgual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonIgual.setText("=");
        jButtonIgual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelCalculadoraLayout = new org.jdesktop.layout.GroupLayout(jPanelCalculadora);
        jPanelCalculadora.setLayout(jPanelCalculadoraLayout);
        jPanelCalculadoraLayout.setHorizontalGroup(
            jPanelCalculadoraLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCalculadoraLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanelCalculadoraLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .add(jTxtResultados)
                    .add(jButtonIgual, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .add(0, 19, Short.MAX_VALUE))
            .add(jPanelCalculadoraLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelCalculadoraLayout.createSequentialGroup()
                    .add(17, 17, 17)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        jPanelCalculadoraLayout.setVerticalGroup(
            jPanelCalculadoraLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCalculadoraLayout.createSequentialGroup()
                .add(4, 4, 4)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtResultados, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 129, Short.MAX_VALUE)
                .add(jButtonIgual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(19, 19, 19))
            .add(jPanelCalculadoraLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelCalculadoraLayout.createSequentialGroup()
                    .add(67, 67, 67)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        jMenuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/16/calculator.png"))); // NOI18N
        jMenuArchivo.setText("Archivo");
        jMenuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArchivoActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Editar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItem1);

        jMenuItem3.setText("Salir");
        jMenuItem3.setToolTipText("Salir de la app");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItem3);

        jMenuBarPrincipal.add(jMenuArchivo);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/16/book-edit.png"))); // NOI18N
        jMenu1.setText("Editar");

        jMenuItem2.setText("Internal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBarPrincipal.add(jMenu1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/16/help.png"))); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBarPrincipal.add(jMenu5);

        setJMenuBar(jMenuBarPrincipal);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelCalculadora, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanelCalculadora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ventanaDialogo ventana = new ventanaDialogo();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuArchivoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        // TODO add your handling code here:
        numero = Double.parseDouble(jTxtResultados.getText());
        

        if (operacion.equals("+")) {
            resultado = (resultado + numero);
            jTxtResultados.setText("" + resultado);
            
        } else if (operacion.equals("-")){
            resultado = (resultado - numero);
            jTxtResultados.setText("" + resultado);
            
        } else if (operacion.equals("*")){
            resultado = (resultado * numero);
            jTxtResultados.setText("" + resultado);
            
        } else if (operacion.equals("/")){
            resultado = (resultado / numero);
            jTxtResultados.setText("" + resultado);
            
        } 

        resultado = 0.0;
        

    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jButtonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPuntoActionPerformed
        // TODO add your handling code here:
        if(jTxtResultados.getText().contains("."))
            jTxtResultados.setText(jTxtResultados.getText().concat(""));
        else
            jTxtResultados.setText(jTxtResultados.getText().concat("."));
    }//GEN-LAST:event_jButtonPuntoActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed

        // TODO add your handling code here:
        jTxtResultados.setText("");
        resultado = 0.0;

    }//GEN-LAST:event_jBtnCActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        if(jTxtResultados.getText().equals("0")){
            jTxtResultados.setText("0");
        }
        else
        jTxtResultados.setText(jTxtResultados.getText().concat("0"));
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignoActionPerformed

        jTxtResultados.getText();
        numero = Double.parseDouble(jTxtResultados.getText());
        if(numero != 0.0)
            resultado = numero * -1;
        else 
            resultado = 0.0;
        jTxtResultados.setText(Double.toString(resultado));
    }//GEN-LAST:event_jButtonSignoActionPerformed

    private void jButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaActionPerformed
        // TODO add your handling code here:
        if (jTxtResultados.getText().equals("")) {
            jTxtResultados.setText("0.0");
        }
        
        numero = Double.parseDouble(jTxtResultados.getText());
        operacion = "+";
        
        if (operacion.equals("-")){
            resultado = (resultado - numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("*")){
            resultado = (resultado * numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("/")){
            resultado = (resultado / numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("x2")){
            resultado = (numero * numero);
            jTxtResultados.setText(Double.toString(resultado));
        } else if (operacion.equals("rz")){
            resultado = Math.sqrt(numero);
            jTxtResultados.setText(Double.toString(resultado));
        }

        operacion = "+";
        resultado = (resultado + numero);
        jTxtResultados.setText("");

    }//GEN-LAST:event_jButtonSumaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jTxtResultados.getText().equals("0")){
            jTxtResultados.setText("3");
        }
        else
        jTxtResultados.setText(jTxtResultados.getText().concat("3"));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jTxtResultados.getText().equals("0")){
            jTxtResultados.setText("2");
        }
        else
        jTxtResultados.setText(jTxtResultados.getText().concat("2"));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTxtResultados.getText().equals("0")){
            jTxtResultados.setText("1");
        }
        else
        jTxtResultados.setText(jTxtResultados.getText().concat("1"));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaActionPerformed
        // TODO add your handling code here:
        if (jTxtResultados.getText().equals("")) {
            jTxtResultados.setText("0.0");
        }
        
        numero = Double.parseDouble(jTxtResultados.getText());
        operacion = "-";

        if (operacion.equals("+")){
            resultado = (resultado + numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("*")){
            resultado = (resultado * numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("/")){
            resultado = (resultado / numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("x2")){
            resultado = (numero * numero);
            jTxtResultados.setText(Double.toString(resultado));
        } else if (operacion.equals("rz")){
            resultado = Math.sqrt(numero);
            jTxtResultados.setText(Double.toString(resultado));
        }

        operacion = "-";
        resultado = (numero - resultado);
        jTxtResultados.setText("");
        
    }//GEN-LAST:event_jButtonRestaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(jTxtResultados.getText().equals("0")){
            jTxtResultados.setText("6");
        }
        else
        jTxtResultados.setText(jTxtResultados.getText().concat("6"));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jTxtResultados.getText().equals("0")){
            jTxtResultados.setText("5");
        }
        else
        jTxtResultados.setText(jTxtResultados.getText().concat("5"));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTxtResultados.getText().equals("0")){
            jTxtResultados.setText("4");
        }
        else
        jTxtResultados.setText(jTxtResultados.getText().concat("4"));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacionActionPerformed
        // TODO add your handling code here:
        if (jTxtResultados.getText().equals("")) {
            jTxtResultados.setText("0.0");
        }
        
        numero = Double.parseDouble(jTxtResultados.getText());
        operacion = "*";

        if (operacion.equals("+")){
            resultado = (resultado + numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("-")){
            resultado = (resultado - numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("/")){
            resultado = (resultado / numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("x2")){
            resultado = (numero * numero);
            jTxtResultados.setText(Double.toString(resultado));
        } else if (operacion.equals("rz")){
            resultado = Math.sqrt(numero);
            jTxtResultados.setText(Double.toString(resultado));
        }

        if (resultado == 0.0) {
            resultado = 1.0;
        }

        
        numero = Double.parseDouble(jTxtResultados.getText());
        resultado = (resultado * numero);
        jTxtResultados.setText("");
    }//GEN-LAST:event_jButtonMultiplicacionActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(jTxtResultados.getText().equals("0")){
            jTxtResultados.setText("9");
        }
        else
        jTxtResultados.setText(jTxtResultados.getText().concat("9"));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(jTxtResultados.getText().equals("0")){
            jTxtResultados.setText("8");
        }
        else
        jTxtResultados.setText(jTxtResultados.getText().concat("8"));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(jTxtResultados.getText().equals("0")){
            jTxtResultados.setText("7");
        }
        else
        jTxtResultados.setText(jTxtResultados.getText().concat("7"));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisionActionPerformed
        // TODO add your handling code here:
        if (jTxtResultados.getText().equals("")) {
            jTxtResultados.setText("0.0");
        }
        
        numero = Double.parseDouble(jTxtResultados.getText());
        operacion = "/";

        if (operacion.equals("+")){
            resultado = (resultado + numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("-")){
            resultado = (resultado - numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("*")){
            resultado = (resultado * numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("x2")){
            resultado = (numero * numero);
            jTxtResultados.setText(Double.toString(resultado));
        } else if (operacion.equals("rz")){
            resultado = Math.sqrt(numero);
            jTxtResultados.setText(Double.toString(resultado));
        }

        if (resultado == 0.0) {
            resultado = 1.0;
        }

        
        numero = Double.parseDouble(jTxtResultados.getText());
        resultado = (numero / resultado);
        jTxtResultados.setText("");
    }//GEN-LAST:event_jButtonDivisionActionPerformed

    private void jButtonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotenciaActionPerformed
        // TODO add your handling code here:
        if (jTxtResultados.getText().equals("")) {
            jTxtResultados.setText("0.0");
        }
        
        numero = Double.parseDouble(jTxtResultados.getText());
        operacion = "x2";

        if (operacion.equals("+")){
            resultado = (resultado + numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("-")){
            resultado = (resultado - numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("*")){
            resultado = (resultado * numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("x2")){
            resultado = (numero * numero);
            jTxtResultados.setText(Double.toString(resultado));
        } else if (operacion.equals("rz")){
            resultado = Math.sqrt(numero);
            jTxtResultados.setText(Double.toString(resultado));
        }

    }//GEN-LAST:event_jButtonPotenciaActionPerformed

    private void jButtonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizActionPerformed
        // TODO add your handling code here:
        if (jTxtResultados.getText().equals("")) {
            jTxtResultados.setText("0.0");
        }
        
        numero = Double.parseDouble(jTxtResultados.getText());
        operacion = "rz";
        
        if (operacion.equals("+")){
            resultado = (resultado + numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("-")){
            resultado = (resultado - numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("*")){
            resultado = (resultado * numero);
            jTxtResultados.setText("");
        } else if (operacion.equals("x2")){
            resultado = (numero * numero);
            jTxtResultados.setText(Double.toString(resultado));
        } else if (operacion.equals("rz")){
            resultado = Math.sqrt(numero);
            jTxtResultados.setText(Double.toString(resultado));
        }

        if (resultado == 0.0) {
            resultado = 1.0;
        }

        

    }//GEN-LAST:event_jButtonRaizActionPerformed

    private void jButtonPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorcentajeActionPerformed
        // TODO add your handling code here:
        if (jTxtResultados.getText().equals("")) {
            jTxtResultados.setText("0.0");
        }
        
        numero = Double.parseDouble(jTxtResultados.getText());
        numero = resultado * (numero / 100);
        jTxtResultados.setText(Double.toString(numero));
        
        
      
        
    }//GEN-LAST:event_jButtonPorcentajeActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        dialogoVentana ventana = new dialogoVentana(this, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        unJInternalFrame internal = new unJInternalFrame();
        internal.setVisible(true);
        add(internal);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraReloaded.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraReloaded.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraReloaded.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraReloaded.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraReloaded().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMultiplicacion;
    private javax.swing.JButton jButtonPorcentaje;
    private javax.swing.JButton jButtonPotencia;
    private javax.swing.JButton jButtonPunto;
    private javax.swing.JButton jButtonRaiz;
    private javax.swing.JButton jButtonResta;
    private javax.swing.JButton jButtonSigno;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCalculadora;
    private javax.swing.JTextField jTxtResultados;
    // End of variables declaration//GEN-END:variables
}
